// src/lib/components/Hero/SolarSystem/planet.svelte
<script lang="ts">
import { T, useLoader, useTask } from "@threlte/core";
import { Mesh, TextureLoader } from "three";
import { useTexture } from "@threlte/extras";

const {
	color,
	radius,
	texture,
	speed = 1,
}: {
	color: string;
	speed?: number;
	radius: number;
	texture?: string;
} = $props();

let ref = $state<Mesh>();
const { load } = useLoader(TextureLoader);

useTask(() => {
	if (ref) {
		ref.rotateY(0.01 * speed);
	}
});
</script>

<T.Mesh bind:ref>
  <T.SphereGeometry args={[radius, 32, 32]} />
  {#if texture}
    {#await load(texture) then map}
      <T.MeshStandardMaterial {map}  />
    {/await}
  {:else}
      <T.MeshStandardMaterial  { color } />
  {/if}
</T.Mesh>

// src/lib/components/ThreeSolarSystem/planet.tsx
import type React from "react";
import type { Mesh } from "three";
import { useRef } from "react";
import { Canvas, useFrame, useThree, useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";

interface PlanetProps {
	color: string;
	speed?: number;
	radius: number;
	texture?: string | null;
	rightClick?: () => void;
}

export const Planet: React.FC<PlanetProps> = ({
	color,
	radius,
	speed = 1,
	texture = null,
    rightClick = () => {},
}) => {
	const ref = useRef<Mesh>(null);
	const _texture = useLoader(
		TextureLoader,
		texture || "/textures/earth_texture.jpg",
	);

	useFrame(() => {
		if (ref.current) {
			ref.current.rotation.y += 0.01 * speed;
		}
	});

	return (
		<>
			<mesh ref={ref} onContextMenu={rightClick}>
				<sphereGeometry args={[radius, 32, 32]} />
				<meshStandardMaterial
					map={texture ? _texture : null}
					color={texture ? undefined : color}
				/>
			</mesh>
		</>
	);
};
